### ISSUE TITLE
can't open app on MacBook Air 15-inch, M2, 2023, 14.6.1 (23G93)

### ISSUE THREAD

**Issue by farffir** [bornfree/dive-color-corrector#10]
Hi,

I get this error. Any ideas?

Thanks,
Rob
<img width="276" alt="Screenshot 2024-09-14 at 8 38 29 AM" src="https://github.com/user-attachments/assets/e181b9c5-f03d-401f-a6c8-98d825907d01">

**Comment by adrianparker** [comment]
I also get that error when trying to open the "Mac Silicon" download.  
If i try it from Terminal, like so
```
adrian@Adrians-MacBook-Air ~ % /Applications/Dive\ Color\ Corrector.app/Contents/MacOS/Dive\ Color\ Corrector 
Traceback (most recent call last):
  File "/Applications/Dive Color Corrector.app/Contents/Resources/__boot__.py", line 161, in <module>
    _run()
  File "/Applications/Dive Color Corrector.app/Contents/Resources/__boot__.py", line 84, in _run
    exec(compile(source, path, "exec"), globals(), globals())
  File "/Applications/Dive Color Corrector.app/Contents/Resources/dcc.py", line 2, in <module>
    import PySimpleGUI as sg
  File "/Applications/Dive Color Corrector.app/Contents/Resources/lib/python3.10/PySimpleGUI/__init__.py", line 2, in <module>
    from .PySimpleGUI import *
  File "/Applications/Dive Color Corrector.app/Contents/Resources/lib/python3.10/PySimpleGUI/PySimpleGUI.py", line 144, in <module>
    tclversion_detailed = tkinter.Tcl().eval('info patchlevel')
  File "tkinter/__init__.pyc", line 2401, in Tcl
  File "tkinter/__init__.pyc", line 2299, in __init__
_tkinter.TclError: Can't find a usable init.tcl in the following directories: 
    /opt/homebrew/Cellar/tcl-tk/8.6.12_1/lib/tcl8.6 {/Applications/Dive Color Corrector.app/Contents/lib/tcl8.6} {/Applications/Dive Color Corrector.app/lib/tcl8.6} {/Applications/Dive Color Corrector.app/Contents/library} {/Applications/Dive Color Corrector.app/library} {/Applications/Dive Color Corrector.app/tcl8.6.12/library} /Applications/tcl8.6.12/library



This probably means that Tcl wasn't installed properly.

2024-11-28 20:39:08.614 Dive Color Corrector[89898:3118292] Launch error
2024-11-28 20:39:08.614 Dive Color Corrector[89898:3118292] Launch error
```

**Comment by adrianparker** [comment]
I was able to get the app to work on my M1 Mac (Apple Silicon) by cloning the repo and following the instructions in README.md.

First time it didn't work with the same error message I get from the download on the front page.
That build, I had only uncommented 'py2app' in requirements.txt.

Then I did what the py2app debig page suggests with install errors... ran this command from the root folder of where I cloned the repo to...
```
dist/dcc.app/Contents/MacOS/dcc
```
Which said it couldn't find "PySimpleGUI".

PySimpleGUI is another item that was commented out in requirements.txt, so I uncommented that too, ran the build process over again including the pip install step, and now dcc.app displays the GUI.  Happy days!

So - @farffir that might work for you too, and @bornfree I wonder if the app listed under 'MacOS (apple Silicon)' here https://bornfree.github.io/dive-color-corrector/ might have been built with the same issue?

Hope that helps someone.

**Comment by stepini** [comment]
Same problem here, I must use only CLI version....
